/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfesionalRouteImport } from './routes/profesional'
import { Route as PacienteRouteImport } from './routes/paciente'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProfesionalIndexRouteImport } from './routes/profesional.index'
import { Route as PacienteIndexRouteImport } from './routes/paciente.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as ProfesionalPerfilRouteImport } from './routes/profesional.perfil'
import { Route as ProfesionalPacientesRouteImport } from './routes/profesional.pacientes'
import { Route as ProfesionalIngresosRouteImport } from './routes/profesional.ingresos'
import { Route as ProfesionalAgendaRouteImport } from './routes/profesional.agenda'
import { Route as ProfesionalActividadesRouteImport } from './routes/profesional.actividades'
import { Route as PacienteTratamientosRouteImport } from './routes/paciente.tratamientos'
import { Route as PacientePerfilRouteImport } from './routes/paciente.perfil'
import { Route as PacientePagosRouteImport } from './routes/paciente.pagos'
import { Route as PacienteModificarRouteImport } from './routes/paciente.modificar'
import { Route as PacienteHorasRouteImport } from './routes/paciente.horas'
import { Route as PacienteAgendarRouteImport } from './routes/paciente.agendar'
import { Route as AdminProfesionalesRouteImport } from './routes/admin.profesionales'
import { Route as AdminPacientesRouteImport } from './routes/admin.pacientes'
import { Route as AdminMaterialesRouteImport } from './routes/admin.materiales'
import { Route as AdminIngresosRouteImport } from './routes/admin.ingresos'
import { Route as AdminGastosRouteImport } from './routes/admin.gastos'
import { Route as AdminFinancieroRouteImport } from './routes/admin.financiero'
import { Route as AdminEspecialidadesRouteImport } from './routes/admin.especialidades'
import { Route as AdminCuotasRouteImport } from './routes/admin.cuotas'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as PublicRegistroRouteImport } from './routes/_public.registro'
import { Route as PublicNosotrosRouteImport } from './routes/_public.nosotros'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as PublicEspecialidadesRouteImport } from './routes/_public.especialidades'
import { Route as PublicContactoRouteImport } from './routes/_public.contacto'

const ProfesionalRoute = ProfesionalRouteImport.update({
  id: '/profesional',
  path: '/profesional',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteRoute = PacienteRouteImport.update({
  id: '/paciente',
  path: '/paciente',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalIndexRoute = ProfesionalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfesionalRoute,
} as any)
const PacienteIndexRoute = PacienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PacienteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ProfesionalPerfilRoute = ProfesionalPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ProfesionalRoute,
} as any)
const ProfesionalPacientesRoute = ProfesionalPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => ProfesionalRoute,
} as any)
const ProfesionalIngresosRoute = ProfesionalIngresosRouteImport.update({
  id: '/ingresos',
  path: '/ingresos',
  getParentRoute: () => ProfesionalRoute,
} as any)
const ProfesionalAgendaRoute = ProfesionalAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ProfesionalRoute,
} as any)
const ProfesionalActividadesRoute = ProfesionalActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => ProfesionalRoute,
} as any)
const PacienteTratamientosRoute = PacienteTratamientosRouteImport.update({
  id: '/tratamientos',
  path: '/tratamientos',
  getParentRoute: () => PacienteRoute,
} as any)
const PacientePerfilRoute = PacientePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PacienteRoute,
} as any)
const PacientePagosRoute = PacientePagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => PacienteRoute,
} as any)
const PacienteModificarRoute = PacienteModificarRouteImport.update({
  id: '/modificar',
  path: '/modificar',
  getParentRoute: () => PacienteRoute,
} as any)
const PacienteHorasRoute = PacienteHorasRouteImport.update({
  id: '/horas',
  path: '/horas',
  getParentRoute: () => PacienteRoute,
} as any)
const PacienteAgendarRoute = PacienteAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => PacienteRoute,
} as any)
const AdminProfesionalesRoute = AdminProfesionalesRouteImport.update({
  id: '/profesionales',
  path: '/profesionales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacientesRoute = AdminPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaterialesRoute = AdminMaterialesRouteImport.update({
  id: '/materiales',
  path: '/materiales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIngresosRoute = AdminIngresosRouteImport.update({
  id: '/ingresos',
  path: '/ingresos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGastosRoute = AdminGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancieroRoute = AdminFinancieroRouteImport.update({
  id: '/financiero',
  path: '/financiero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEspecialidadesRoute = AdminEspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuotasRoute = AdminCuotasRouteImport.update({
  id: '/cuotas',
  path: '/cuotas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const PublicRegistroRoute = PublicRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNosotrosRoute = PublicNosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEspecialidadesRoute = PublicEspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactoRoute = PublicContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/paciente': typeof PacienteRouteWithChildren
  '/profesional': typeof ProfesionalRouteWithChildren
  '/contacto': typeof PublicContactoRoute
  '/especialidades': typeof PublicEspecialidadesRoute
  '/login': typeof PublicLoginRoute
  '/nosotros': typeof PublicNosotrosRoute
  '/registro': typeof PublicRegistroRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/cuotas': typeof AdminCuotasRoute
  '/admin/especialidades': typeof AdminEspecialidadesRoute
  '/admin/financiero': typeof AdminFinancieroRoute
  '/admin/gastos': typeof AdminGastosRoute
  '/admin/ingresos': typeof AdminIngresosRoute
  '/admin/materiales': typeof AdminMaterialesRoute
  '/admin/pacientes': typeof AdminPacientesRoute
  '/admin/profesionales': typeof AdminProfesionalesRoute
  '/paciente/agendar': typeof PacienteAgendarRoute
  '/paciente/horas': typeof PacienteHorasRoute
  '/paciente/modificar': typeof PacienteModificarRoute
  '/paciente/pagos': typeof PacientePagosRoute
  '/paciente/perfil': typeof PacientePerfilRoute
  '/paciente/tratamientos': typeof PacienteTratamientosRoute
  '/profesional/actividades': typeof ProfesionalActividadesRoute
  '/profesional/agenda': typeof ProfesionalAgendaRoute
  '/profesional/ingresos': typeof ProfesionalIngresosRoute
  '/profesional/pacientes': typeof ProfesionalPacientesRoute
  '/profesional/perfil': typeof ProfesionalPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/paciente/': typeof PacienteIndexRoute
  '/profesional/': typeof ProfesionalIndexRoute
}
export interface FileRoutesByTo {
  '/contacto': typeof PublicContactoRoute
  '/especialidades': typeof PublicEspecialidadesRoute
  '/login': typeof PublicLoginRoute
  '/nosotros': typeof PublicNosotrosRoute
  '/registro': typeof PublicRegistroRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/cuotas': typeof AdminCuotasRoute
  '/admin/especialidades': typeof AdminEspecialidadesRoute
  '/admin/financiero': typeof AdminFinancieroRoute
  '/admin/gastos': typeof AdminGastosRoute
  '/admin/ingresos': typeof AdminIngresosRoute
  '/admin/materiales': typeof AdminMaterialesRoute
  '/admin/pacientes': typeof AdminPacientesRoute
  '/admin/profesionales': typeof AdminProfesionalesRoute
  '/paciente/agendar': typeof PacienteAgendarRoute
  '/paciente/horas': typeof PacienteHorasRoute
  '/paciente/modificar': typeof PacienteModificarRoute
  '/paciente/pagos': typeof PacientePagosRoute
  '/paciente/perfil': typeof PacientePerfilRoute
  '/paciente/tratamientos': typeof PacienteTratamientosRoute
  '/profesional/actividades': typeof ProfesionalActividadesRoute
  '/profesional/agenda': typeof ProfesionalAgendaRoute
  '/profesional/ingresos': typeof ProfesionalIngresosRoute
  '/profesional/pacientes': typeof ProfesionalPacientesRoute
  '/profesional/perfil': typeof ProfesionalPerfilRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/paciente': typeof PacienteIndexRoute
  '/profesional': typeof ProfesionalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/paciente': typeof PacienteRouteWithChildren
  '/profesional': typeof ProfesionalRouteWithChildren
  '/_public/contacto': typeof PublicContactoRoute
  '/_public/especialidades': typeof PublicEspecialidadesRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/nosotros': typeof PublicNosotrosRoute
  '/_public/registro': typeof PublicRegistroRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/cuotas': typeof AdminCuotasRoute
  '/admin/especialidades': typeof AdminEspecialidadesRoute
  '/admin/financiero': typeof AdminFinancieroRoute
  '/admin/gastos': typeof AdminGastosRoute
  '/admin/ingresos': typeof AdminIngresosRoute
  '/admin/materiales': typeof AdminMaterialesRoute
  '/admin/pacientes': typeof AdminPacientesRoute
  '/admin/profesionales': typeof AdminProfesionalesRoute
  '/paciente/agendar': typeof PacienteAgendarRoute
  '/paciente/horas': typeof PacienteHorasRoute
  '/paciente/modificar': typeof PacienteModificarRoute
  '/paciente/pagos': typeof PacientePagosRoute
  '/paciente/perfil': typeof PacientePerfilRoute
  '/paciente/tratamientos': typeof PacienteTratamientosRoute
  '/profesional/actividades': typeof ProfesionalActividadesRoute
  '/profesional/agenda': typeof ProfesionalAgendaRoute
  '/profesional/ingresos': typeof ProfesionalIngresosRoute
  '/profesional/pacientes': typeof ProfesionalPacientesRoute
  '/profesional/perfil': typeof ProfesionalPerfilRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/paciente/': typeof PacienteIndexRoute
  '/profesional/': typeof ProfesionalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/paciente'
    | '/profesional'
    | '/contacto'
    | '/especialidades'
    | '/login'
    | '/nosotros'
    | '/registro'
    | '/admin/agenda'
    | '/admin/cuotas'
    | '/admin/especialidades'
    | '/admin/financiero'
    | '/admin/gastos'
    | '/admin/ingresos'
    | '/admin/materiales'
    | '/admin/pacientes'
    | '/admin/profesionales'
    | '/paciente/agendar'
    | '/paciente/horas'
    | '/paciente/modificar'
    | '/paciente/pagos'
    | '/paciente/perfil'
    | '/paciente/tratamientos'
    | '/profesional/actividades'
    | '/profesional/agenda'
    | '/profesional/ingresos'
    | '/profesional/pacientes'
    | '/profesional/perfil'
    | '/admin/'
    | '/paciente/'
    | '/profesional/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contacto'
    | '/especialidades'
    | '/login'
    | '/nosotros'
    | '/registro'
    | '/admin/agenda'
    | '/admin/cuotas'
    | '/admin/especialidades'
    | '/admin/financiero'
    | '/admin/gastos'
    | '/admin/ingresos'
    | '/admin/materiales'
    | '/admin/pacientes'
    | '/admin/profesionales'
    | '/paciente/agendar'
    | '/paciente/horas'
    | '/paciente/modificar'
    | '/paciente/pagos'
    | '/paciente/perfil'
    | '/paciente/tratamientos'
    | '/profesional/actividades'
    | '/profesional/agenda'
    | '/profesional/ingresos'
    | '/profesional/pacientes'
    | '/profesional/perfil'
    | '/'
    | '/admin'
    | '/paciente'
    | '/profesional'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/paciente'
    | '/profesional'
    | '/_public/contacto'
    | '/_public/especialidades'
    | '/_public/login'
    | '/_public/nosotros'
    | '/_public/registro'
    | '/admin/agenda'
    | '/admin/cuotas'
    | '/admin/especialidades'
    | '/admin/financiero'
    | '/admin/gastos'
    | '/admin/ingresos'
    | '/admin/materiales'
    | '/admin/pacientes'
    | '/admin/profesionales'
    | '/paciente/agendar'
    | '/paciente/horas'
    | '/paciente/modificar'
    | '/paciente/pagos'
    | '/paciente/perfil'
    | '/paciente/tratamientos'
    | '/profesional/actividades'
    | '/profesional/agenda'
    | '/profesional/ingresos'
    | '/profesional/pacientes'
    | '/profesional/perfil'
    | '/_public/'
    | '/admin/'
    | '/paciente/'
    | '/profesional/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  PacienteRoute: typeof PacienteRouteWithChildren
  ProfesionalRoute: typeof ProfesionalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profesional': {
      id: '/profesional'
      path: '/profesional'
      fullPath: '/profesional'
      preLoaderRoute: typeof ProfesionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente': {
      id: '/paciente'
      path: '/paciente'
      fullPath: '/paciente'
      preLoaderRoute: typeof PacienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional/': {
      id: '/profesional/'
      path: '/'
      fullPath: '/profesional/'
      preLoaderRoute: typeof ProfesionalIndexRouteImport
      parentRoute: typeof ProfesionalRoute
    }
    '/paciente/': {
      id: '/paciente/'
      path: '/'
      fullPath: '/paciente/'
      preLoaderRoute: typeof PacienteIndexRouteImport
      parentRoute: typeof PacienteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/profesional/perfil': {
      id: '/profesional/perfil'
      path: '/perfil'
      fullPath: '/profesional/perfil'
      preLoaderRoute: typeof ProfesionalPerfilRouteImport
      parentRoute: typeof ProfesionalRoute
    }
    '/profesional/pacientes': {
      id: '/profesional/pacientes'
      path: '/pacientes'
      fullPath: '/profesional/pacientes'
      preLoaderRoute: typeof ProfesionalPacientesRouteImport
      parentRoute: typeof ProfesionalRoute
    }
    '/profesional/ingresos': {
      id: '/profesional/ingresos'
      path: '/ingresos'
      fullPath: '/profesional/ingresos'
      preLoaderRoute: typeof ProfesionalIngresosRouteImport
      parentRoute: typeof ProfesionalRoute
    }
    '/profesional/agenda': {
      id: '/profesional/agenda'
      path: '/agenda'
      fullPath: '/profesional/agenda'
      preLoaderRoute: typeof ProfesionalAgendaRouteImport
      parentRoute: typeof ProfesionalRoute
    }
    '/profesional/actividades': {
      id: '/profesional/actividades'
      path: '/actividades'
      fullPath: '/profesional/actividades'
      preLoaderRoute: typeof ProfesionalActividadesRouteImport
      parentRoute: typeof ProfesionalRoute
    }
    '/paciente/tratamientos': {
      id: '/paciente/tratamientos'
      path: '/tratamientos'
      fullPath: '/paciente/tratamientos'
      preLoaderRoute: typeof PacienteTratamientosRouteImport
      parentRoute: typeof PacienteRoute
    }
    '/paciente/perfil': {
      id: '/paciente/perfil'
      path: '/perfil'
      fullPath: '/paciente/perfil'
      preLoaderRoute: typeof PacientePerfilRouteImport
      parentRoute: typeof PacienteRoute
    }
    '/paciente/pagos': {
      id: '/paciente/pagos'
      path: '/pagos'
      fullPath: '/paciente/pagos'
      preLoaderRoute: typeof PacientePagosRouteImport
      parentRoute: typeof PacienteRoute
    }
    '/paciente/modificar': {
      id: '/paciente/modificar'
      path: '/modificar'
      fullPath: '/paciente/modificar'
      preLoaderRoute: typeof PacienteModificarRouteImport
      parentRoute: typeof PacienteRoute
    }
    '/paciente/horas': {
      id: '/paciente/horas'
      path: '/horas'
      fullPath: '/paciente/horas'
      preLoaderRoute: typeof PacienteHorasRouteImport
      parentRoute: typeof PacienteRoute
    }
    '/paciente/agendar': {
      id: '/paciente/agendar'
      path: '/agendar'
      fullPath: '/paciente/agendar'
      preLoaderRoute: typeof PacienteAgendarRouteImport
      parentRoute: typeof PacienteRoute
    }
    '/admin/profesionales': {
      id: '/admin/profesionales'
      path: '/profesionales'
      fullPath: '/admin/profesionales'
      preLoaderRoute: typeof AdminProfesionalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pacientes': {
      id: '/admin/pacientes'
      path: '/pacientes'
      fullPath: '/admin/pacientes'
      preLoaderRoute: typeof AdminPacientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materiales': {
      id: '/admin/materiales'
      path: '/materiales'
      fullPath: '/admin/materiales'
      preLoaderRoute: typeof AdminMaterialesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ingresos': {
      id: '/admin/ingresos'
      path: '/ingresos'
      fullPath: '/admin/ingresos'
      preLoaderRoute: typeof AdminIngresosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gastos': {
      id: '/admin/gastos'
      path: '/gastos'
      fullPath: '/admin/gastos'
      preLoaderRoute: typeof AdminGastosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financiero': {
      id: '/admin/financiero'
      path: '/financiero'
      fullPath: '/admin/financiero'
      preLoaderRoute: typeof AdminFinancieroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/especialidades': {
      id: '/admin/especialidades'
      path: '/especialidades'
      fullPath: '/admin/especialidades'
      preLoaderRoute: typeof AdminEspecialidadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cuotas': {
      id: '/admin/cuotas'
      path: '/cuotas'
      fullPath: '/admin/cuotas'
      preLoaderRoute: typeof AdminCuotasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/registro': {
      id: '/_public/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof PublicRegistroRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/nosotros': {
      id: '/_public/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof PublicNosotrosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/especialidades': {
      id: '/_public/especialidades'
      path: '/especialidades'
      fullPath: '/especialidades'
      preLoaderRoute: typeof PublicEspecialidadesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contacto': {
      id: '/_public/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof PublicContactoRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicContactoRoute: typeof PublicContactoRoute
  PublicEspecialidadesRoute: typeof PublicEspecialidadesRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicNosotrosRoute: typeof PublicNosotrosRoute
  PublicRegistroRoute: typeof PublicRegistroRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContactoRoute: PublicContactoRoute,
  PublicEspecialidadesRoute: PublicEspecialidadesRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicNosotrosRoute: PublicNosotrosRoute,
  PublicRegistroRoute: PublicRegistroRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminCuotasRoute: typeof AdminCuotasRoute
  AdminEspecialidadesRoute: typeof AdminEspecialidadesRoute
  AdminFinancieroRoute: typeof AdminFinancieroRoute
  AdminGastosRoute: typeof AdminGastosRoute
  AdminIngresosRoute: typeof AdminIngresosRoute
  AdminMaterialesRoute: typeof AdminMaterialesRoute
  AdminPacientesRoute: typeof AdminPacientesRoute
  AdminProfesionalesRoute: typeof AdminProfesionalesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminCuotasRoute: AdminCuotasRoute,
  AdminEspecialidadesRoute: AdminEspecialidadesRoute,
  AdminFinancieroRoute: AdminFinancieroRoute,
  AdminGastosRoute: AdminGastosRoute,
  AdminIngresosRoute: AdminIngresosRoute,
  AdminMaterialesRoute: AdminMaterialesRoute,
  AdminPacientesRoute: AdminPacientesRoute,
  AdminProfesionalesRoute: AdminProfesionalesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PacienteRouteChildren {
  PacienteAgendarRoute: typeof PacienteAgendarRoute
  PacienteHorasRoute: typeof PacienteHorasRoute
  PacienteModificarRoute: typeof PacienteModificarRoute
  PacientePagosRoute: typeof PacientePagosRoute
  PacientePerfilRoute: typeof PacientePerfilRoute
  PacienteTratamientosRoute: typeof PacienteTratamientosRoute
  PacienteIndexRoute: typeof PacienteIndexRoute
}

const PacienteRouteChildren: PacienteRouteChildren = {
  PacienteAgendarRoute: PacienteAgendarRoute,
  PacienteHorasRoute: PacienteHorasRoute,
  PacienteModificarRoute: PacienteModificarRoute,
  PacientePagosRoute: PacientePagosRoute,
  PacientePerfilRoute: PacientePerfilRoute,
  PacienteTratamientosRoute: PacienteTratamientosRoute,
  PacienteIndexRoute: PacienteIndexRoute,
}

const PacienteRouteWithChildren = PacienteRoute._addFileChildren(
  PacienteRouteChildren,
)

interface ProfesionalRouteChildren {
  ProfesionalActividadesRoute: typeof ProfesionalActividadesRoute
  ProfesionalAgendaRoute: typeof ProfesionalAgendaRoute
  ProfesionalIngresosRoute: typeof ProfesionalIngresosRoute
  ProfesionalPacientesRoute: typeof ProfesionalPacientesRoute
  ProfesionalPerfilRoute: typeof ProfesionalPerfilRoute
  ProfesionalIndexRoute: typeof ProfesionalIndexRoute
}

const ProfesionalRouteChildren: ProfesionalRouteChildren = {
  ProfesionalActividadesRoute: ProfesionalActividadesRoute,
  ProfesionalAgendaRoute: ProfesionalAgendaRoute,
  ProfesionalIngresosRoute: ProfesionalIngresosRoute,
  ProfesionalPacientesRoute: ProfesionalPacientesRoute,
  ProfesionalPerfilRoute: ProfesionalPerfilRoute,
  ProfesionalIndexRoute: ProfesionalIndexRoute,
}

const ProfesionalRouteWithChildren = ProfesionalRoute._addFileChildren(
  ProfesionalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  PacienteRoute: PacienteRouteWithChildren,
  ProfesionalRoute: ProfesionalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
